version: "3.3"

services:
  kafka-registration-websocket-server:
    build:
      context: .
      target: test
    ports:
      - "8080:8080"
    depends_on:
      - kafka
      - mock-registration-api
    environment:
      ICON_REGISTRATION_WEBSOCKET_OUTPUT_TOPIC: outputs
      ICON_REGISTRATION_WEBSOCKET_BROKER_URL: kafka:9092
      ICON_REGISTRATION_WEBSOCKET_REGISTRATION_URL: mock-registration-api:8888
      ICON_REGISTRATION_WEBSOCKET_PORT: 8080
      ICON_REGISTRATION_WEBSOCKET_PREFIX: ""

  mock-registration-api:
    build:
      context: ./test/mock-registration-api/
      target: prod
    ports:
      - "8888:8888"
    environment:
      MOCK_REGISTRATION_API_PORT: "8888"

  zookeeper:
    image: confluentinc/cp-zookeeper:5.0.1-1
    ports:
      - "2181:2181"
    environment:
      zk_id: "1"
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - default

  kafka:
    image: confluentinc/cp-enterprise-kafka:5.5.3
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://35.160.158.191:29092
      KAFKA_BROKER_ID: 1
      KAFKA_BROKER_RACK: "r1"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_JMX_PORT: 9991

